import esbuild from 'esbuild';
import process from 'process';

const isProduction = process.argv.includes('--production');

const buildOptions = {
	entryPoints: ['src/main.js'],
	bundle: true,
	format: 'cjs',
	target: 'es2018',
	platform: 'node',
	outfile: 'main.js',
	external: ['obsidian'],
	banner: {
		js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`,
	},
	footer: {
		js: `if (module.exports.default) module.exports = module.exports.default;`
	},
	minify: isProduction,
	sourcemap: !isProduction,
	treeShaking: true,
	allowOverwrite: true,
};

// Build
await esbuild.build(buildOptions).catch(() => process.exit(1));

